version: '3.8'

services:
  wooper-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wooper-bot
    restart: unless-stopped
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    env_file:
      - .env
    volumes:
      # Mount image directory for easy updates
      - ./img:/app/img:ro
    # Health check
    healthcheck:
      test: ["CMD", "pgrep", "wooper-bot"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits (adjust as needed)
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
